### ISSUE TITLE
Is there any way to return job id 

### ISSUE THREAD

**Issue by asheikm** [lahdekorpi/node-salt-api#12]
hi 

Is there anyway to return salt job id , say for example when highstating a server though salt api and return job id for that ,

**Comment by lahdekorpi** [comment]
Unfortunately at the moment no, the API doesn't return the jid for the call this library is making.

I will be implementing the `POST /minion` API call soon for these cases where you want to start something without waiting for the results immediately.

**Comment by lahdekorpi** [comment]
For reference: https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Minions.POST

**Comment by lahdekorpi** [comment]
This will be implemented in #19
