### ISSUE TITLE
axios instead of request-promise-native ?

### ISSUE THREAD

**Issue by asheikm** [lahdekorpi/node-salt-api#18]
Since reuqst promise-native has been depercated for quite some time, is there anyway to replace that with axios or any other stable   packages ?

**Comment by lahdekorpi** [comment]
Hi @asheikm and thanks for the feedback! Axios would be nice, but while deprecated, there is luckily no immediate danger until a full rewrite of this library.

I'm planning on rewriting the whole library by the end of the year. I opened a new issue #19 for any suggestions.

**Comment by lahdekorpi** [comment]
@asheikm https://github.com/lahdekorpi/node-salt-api/tree/next
