### ISSUE TITLE
Request to Salt-API does not implicitly set a value for body

### ISSUE THREAD

**Issue by dave92082** [lahdekorpi/node-salt-api#5]
When an array is passed in as part of the body, the Request library does not correctly submit the data to the Salt-API.

**Comment by dave92082** [comment]
Not an issue, I was looking at the NPM version of the lib instead of the Git version. Any way you can publish the latest to NPM? That would resolve this issue

**Comment by lahdekorpi** [comment]
Sorry, I thought I already published it. Thanks for the info and contribution.
NPM version is not at 1.1.0.
